package site.ilemon.parser;

import site.ilemon.ast.Ast;
import site.ilemon.lexer.Lexer;
import site.ilemon.lexer.Token;
import site.ilemon.lexer.TokenKind;
import site.ilemon.exception.ParseException;
import site.ilemon.diagnostic.Diagnostic;
import site.ilemon.diagnostic.DiagnosticEngine;
import site.ilemon.exception.CompilerException;

import java.io.IOException;
import java.util.ArrayList;

import static site.ilemon.lexer.TokenKind.Num;


/**
 * Recursive descent parser.
 *
 * <p>Parses the token stream generated by {@link Lexer} according to the Lemon
 * BNF grammar and builds an Abstract Syntax Tree (AST). Employs a top-down LL(2)
 * parsing strategy using {@code lookahead(1)} / {@code lookahead(2)} to resolve
 * grammar ambiguities.</p>
 *
 * <h3>Core Grammar Rules</h3>
 * <pre>
 * program    ::= "class" id "{" method* "}"
 * method     ::= type id "(" params? ")" "{" varDecl* stmt* "}"
 * stmt       ::= assign | if | while | block | return | printf | call
 * expr       ::= andExpr ("||" andExpr)*    -- operator precedence from lowest to highest
 * </pre>
 *
 * <h3>Usage Example</h3>
 * <pre>
 * Lexer lexer = new Lexer(new File("Hello.lemon"));
 * Parser parser = new Parser(lexer);
 * Ast.Program.T ast = parser.parse();
 * </pre>
 *
 * @author andy
 * @see Lexer
 * @see Ast.Program
 */
public class Parser {

	private Lexer lexer; // Lexer instance

	private Token look;  // Current token
	private final DiagnosticEngine diagnosticEngine;

	public Parser(Lexer lexer) throws IOException{
		this.lexer=lexer;
		this.diagnosticEngine = new DiagnosticEngine();
		lexer.lexicalAnalysis();
		move();
	}

	public DiagnosticEngine getDiagnosticEngine() {
		return diagnosticEngine;
	}

	public java.util.List<Diagnostic> getDiagnostics() {
		return diagnosticEngine.diagnostics();
	}

	/**
	 * Read the next token.
	 */
	private void move() {
		look = lexer.next();
	}


	/**
	 * Match {@code token} with the current token from the lexer.
	 * @param lexeme
	 * @throws IOException
	 */
	private void match(String lexeme) throws IOException{
		if( lexeme.equals(look.lexeme))
			move();
		else
			expected(lexeme);
	}
	
	private void match(Token token) throws IOException{
		if( token.kind == look.kind ){
			move();
		}else{
			expected(token.kind.toString());
		}
	}

	private void expected(String s) {
		String suggestion = isInsertableToken(s) ? s : null;
		throw diagnosticException(site.ilemon.diagnostic.DiagnosticCodes.PARSE_EXPECTED_TOKEN, "syntax error: expected '" + s
				+ "', but found '" + look.lexeme + "'", suggestion);
	}

	private void error(String message) {
		throw diagnosticException(site.ilemon.diagnostic.DiagnosticCodes.PARSE_INVALID_CONSTRUCT, message + "; current token is '" + look.lexeme + "'");
	}

	private void error(String message, String suggestion) {
		throw diagnosticException(site.ilemon.diagnostic.DiagnosticCodes.PARSE_INVALID_CONSTRUCT, message + "; current token is '" + look.lexeme + "'", suggestion);
	}

	private ParseException diagnosticException(String code, String message) {
		return diagnosticException(code, message, null);
	}

	private ParseException diagnosticException(String code, String message, String suggestion) {
		var builder = diagnosticEngine.error(code)
				.message(formatError(message))
				.primary(tokenSpan(look), "here");
		if (suggestion != null && tokenSpan(look) != null) {
			var span = tokenSpan(look);
			var insertion = site.ilemon.util.SourceSpan.singlePoint(span.getFileName(), span.getStartOffset(),
					span.getStartLine(), span.getStartColumn());
			builder.suggestion(insertion, suggestion, "insert '" + suggestion + "'");
		}
		Diagnostic diagnostic = builder.report();
		return new ParseException(diagnostic);
	}

	private boolean isInsertableToken(String token) {
		return token != null && token.length() <= 2
				&& !token.equals("Id") && !token.equals("Num") && !token.equals("EOF");
	}

	private site.ilemon.util.SourceSpan tokenSpan(Token token) {
		return token == null ? null : token.getSpan();
	}

	/**
	 * Entry point for error formatting.
	 * @return Program
	 * @throws IOException
	 */
	private String formatError(String message) {
		String sourceLine = lexer.getSourceLine(look.lineNumber);
		StringBuilder result = new StringBuilder();
		result.append(String.format("[parser] line %d, column %d: %s",
				look.lineNumber, look.columnNumber, message));
		if (sourceLine != null && !sourceLine.isEmpty()) {
			result.append(System.lineSeparator());
			result.append("    ").append(sourceLine).append(System.lineSeparator());
			result.append("    ");
			for (int i = 1; i < look.columnNumber; i++) {
				result.append(' ');
			}
			result.append('^');
		}
		return result.toString();
	}

	public Ast.Program.T parse() throws IOException{
		Ast.MainClass.MainClassSingle mainClass;
		ParseException firstFailure = null;
		try {
			mainClass = parseMainClass();
		} catch (ParseException failure) {
			firstFailure = failure;
			synchronizeTo(TokenKind.EOF);
			mainClass = new Ast.MainClass.MainClassSingle(lexer.getClassName(), null, new ArrayList<>());
		}
		if (firstFailure != null) {
			throw firstFailure;
		}
		if (diagnosticEngine.hasErrors()) {
			throw new ParseException(diagnosticEngine.diagnostics().get(0));
		}
		Ast.Program.T programSingle = new Ast.Program.ProgramSingle(mainClass);
		return programSingle;
	}


	// <mainClass> -> class <name> { <methodList>}
	private Ast.MainClass.MainClassSingle parseMainClass() throws IOException {
		Ast.MainClass.MainClassSingle mainClass = null;
		match("class");
		String className = look.lexeme;
		// Check if class name matches the file name
		if( !className.equals(lexer.getClassName()) ){
			this.error(String.format("class name '%s' does not match file name '%s'", className, lexer.getClassName()));
		}
		move();
		match("{");
		ArrayList<Ast.Method.T> methods = parseMethodList();
		mainClass = new Ast.MainClass.MainClassSingle(className,null,methods);
		if (look.kind == TokenKind.Rbrace) {
			match("}");
		} else if (!diagnosticEngine.hasErrors()) {
			expected("}");
		}
		if (look.kind != TokenKind.EOF && !diagnosticEngine.hasErrors()) {
			match("EOF");
		}
		return mainClass;
	}

	// <methodList> -> <method>*
	private ArrayList<Ast.Method.T> parseMethodList() throws IOException {
		ArrayList<Ast.Method.T> methods = new ArrayList<>();
		while (isMethodStart()) {
			try {
				methods.add(parseMethod());
			} catch (ParseException failure) {
				synchronizeToMethodBoundary();
			}
		}
		return methods;
	}

	private boolean isMethodStart() {
		return look != null && (look.kind == TokenKind.Void || look.kind == TokenKind.Int
				|| look.kind == TokenKind.Float || look.kind == TokenKind.Double
				|| look.kind == TokenKind.Bool || look.kind == TokenKind.Byte || look.kind == TokenKind.Short || look.kind == TokenKind.Char || look.kind == TokenKind.Long || look.kind == TokenKind.String);
	}

	private void synchronizeToMethodBoundary() {
		while (look != null && look.kind != TokenKind.EOF && look.kind != TokenKind.Rbrace
				&& !isMethodStart()) {
			move();
		}
	}

	private void synchronizeTo(TokenKind boundary) {
		while (look != null && look.kind != boundary) {
			move();
		}
	}

	
	// <method> -> void | int | double | methodname ( <inputparams> ) {<varDeclares> <stmts> [return <expr>]}
	private Ast.Method.MethodSingle parseMethod() throws IOException {
		Ast.Type.T t = parseType();
		if (look.kind == TokenKind.Lbracket) {
			match("[");
			match("]");
			t = createArrayType(t, -1);
		}
		String methodName = look.lexeme;
		int lineNumber = look.lineNumber;
		Token nameToken = look;
		move();
		match("(");
			ArrayList<Ast.Declare.T> inputParams = parseInputParams();
		match(")");
		match("{");
		ArrayList<Ast.Declare.T> localParams = parseVarDeclares();
		ArrayList<Ast.Stmt.T> stmts = parseStmts();
		match("}");
		Ast.Stmt.T stmt = stmts.isEmpty() ? null : stmts.get(stmts.size()-1);
		Ast.Method.MethodSingle method = new Ast.Method.MethodSingle(t,methodName,inputParams,localParams,stmts,stmt,lineNumber);
		method.setSpan(tokenSpan(nameToken));
		if( !methodName.equals("main")){
			return method;
		}else{
			method.setRetExp(null);
			return method;
		}

	}

	// <varDeclares> -> <varDeclare>*
	private ArrayList<Ast.Declare.T> parseVarDeclares() throws IOException{
		ArrayList<Ast.Declare.T> rs = new ArrayList<>();
		while(isVarDeclarationStart()){
			rs.add(parseDeclare());
		}
		return rs;

	}

	private boolean isVarDeclarationStart() {
		if (!isTypeToken(look.kind)) {
			return false;
		}
		Token id = lexer.lookahead(1);
		return id != null && id.kind == TokenKind.Id;
	}

	// // <declare> -> type id; | type id[size];
	private Ast.Declare.T parseDeclare() throws IOException {
		Ast.Type.T type = parseType();
		if( look.kind == TokenKind.Id ){
			Token idToken = look;
			String id = look.lexeme;
			int lineNumber = look.lineNumber;
			move();
			// type id[size]; - Array declaration
			if( look.kind == TokenKind.Lbracket) {
				match("[");
				int size;
				try {
					size = Integer.parseInt(look.lexeme);
				} catch (NumberFormatException e) {
					error(String.format("array size must be an integer, but found: '%s'", look.lexeme));
					return null;
				}
				if( size <= 0 ){
					error(String.format("array size must be positive, but found: %d", size));
					return null;
				}
				match(new Token(TokenKind.Num));
				match("]");
				match(";");
				// Create array type based on element type
				Ast.Type.T arrayType = createArrayType(type, size);
				if( arrayType == null ){
					error(String.format("unsupported array element type: %s", type));
					return null;
				}
				Ast.Declare.DeclareSingle declaration = new Ast.Declare.DeclareSingle(arrayType, id, lineNumber);
				declaration.setSpan(tokenSpan(idToken));
				return declaration;
			}
			// type id;
			else if( look.kind == TokenKind.Semicolon) {
				Ast.Declare.DeclareSingle d = new Ast.Declare.DeclareSingle(type,id,lineNumber);
				d.setSpan(tokenSpan(idToken));
				match(";");
				return d;
			}
			else {
				error(String.format("invalid variable declaration for '%s'; expected ';' or an array declarator", id), ";");
				return null;
			}

		}else {
			error("invalid declaration: a type must be followed by a variable name");
			return null;
		}
	}

	// Create array type based on element type
	private Ast.Type.T createArrayType(Ast.Type.T baseType, int size) {
		if (baseType instanceof Ast.Type.Int) {
			return new Ast.Type.IntArray(size);
		} else if (baseType instanceof Ast.Type.Byte) {
			return new Ast.Type.ByteArray(size);
		} else if (baseType instanceof Ast.Type.Short) {
			return new Ast.Type.ShortArray(size);
		} else if (baseType instanceof Ast.Type.Char) {
			return new Ast.Type.CharArray(size);
		} else if (baseType instanceof Ast.Type.Long) {
			return new Ast.Type.LongArray(size);
		} else if (baseType instanceof Ast.Type.Float) {
			return new Ast.Type.FloatArray(size);
		} else if (baseType instanceof Ast.Type.Double) {
			return new Ast.Type.DoubleArray(size);
		} else if (baseType instanceof Ast.Type.Bool) {
			return new Ast.Type.BoolArray(size);
		} else if (baseType instanceof Ast.Type.Str) {
			return new Ast.Type.StringArray(size);
		}
		return null;
	}

	// <inputparams> -> <formalParam> ("," <formalParam>)*
	private ArrayList<Ast.Declare.T> parseInputParams() throws IOException {
		ArrayList<Ast.Declare.T> rs = new ArrayList<>();
		if( isTypeToken(look.kind) ){
			rs.add(parseFormalParam());
			while(look.kind == TokenKind.Comma ){
				move();
				rs.add(parseFormalParam());
			}
		}
		return rs;
	}

	// <formalParam> -> type id | type id "[" "]"
	private Ast.Declare.T parseFormalParam() throws IOException {
		Ast.Type.T type = parseType();
		String id = look.lexeme;
		Token idToken = look;
		int lineNumber = look.lineNumber;
		match(new Token(TokenKind.Id));
		if (look.kind == TokenKind.Lbracket) {
			match("[");
			match("]");
			Ast.Type.T arrayType = createArrayType(type, -1);
			if (arrayType == null) {
				error(String.format("unsupported array parameter element type: %s", type));
				return null;
			}
			type = arrayType;
		}
		Ast.Declare.DeclareSingle declaration = new Ast.Declare.DeclareSingle(type, id, lineNumber);
		declaration.setSpan(tokenSpan(idToken));
		return declaration;
	}

	/**
	 * Check whether the current token is a type keyword.
	 */
	private boolean isTypeToken(TokenKind kind) {
		return kind == TokenKind.Int || kind == TokenKind.Float
				|| kind == TokenKind.Double || kind == TokenKind.Bool || kind == TokenKind.Byte || kind == TokenKind.Short || kind == TokenKind.Char || kind == TokenKind.Long || kind == TokenKind.String;
	}


	private Ast.Type.T parseType() {
		if( look.kind == TokenKind.Int ){
			move();
			return new Ast.Type.Int();
		}
		else if(look.kind == TokenKind.Void){
			move();
			return new Ast.Type.Void();
		}
		else if(look.kind == TokenKind.Float){
			move();
			return new Ast.Type.Float();
		}
		else if(look.kind == TokenKind.Double){
			move();
			return new Ast.Type.Double();
		}
		else if(look.kind == TokenKind.Bool){
			move();
			return new Ast.Type.Bool();
		}
		else if(look.kind == TokenKind.Byte){
			move();
			return new Ast.Type.Byte();
		}
		else if(look.kind == TokenKind.Short){
			move();
			return new Ast.Type.Short();
		}
		else if(look.kind == TokenKind.Char){
			move();
			return new Ast.Type.Char();
		}
		else if(look.kind == TokenKind.Long){
			move();
			return new Ast.Type.Long();
		}
		else if(look.kind == TokenKind.String){
			move();
			return new Ast.Type.Str();
		}
		else 
			error("expected type keyword int, float, double, bool, byte, short, char, long, string, or void");
		return null;
	}

	private ArrayList<Ast.Stmt.T> parseStmts() throws IOException {
		ArrayList<Ast.Stmt.T> rs = new ArrayList<>();
		while (isStatementStart()) {
			try {
				rs.add(parseStmt());
			} catch (ParseException failure) {
				synchronizeToStatementBoundary();
			}
		}
		return rs;
	}

	private boolean isStatementStart() {
		return look != null && (look.kind == TokenKind.Printf || look.kind == TokenKind.PrintLine
				|| look.kind == TokenKind.If || look.kind == TokenKind.While || look.kind == TokenKind.For
				|| look.kind == TokenKind.Lbrace || look.kind == TokenKind.Id
				|| look.kind == TokenKind.Break || look.kind == TokenKind.Continue
				|| look.kind == TokenKind.Return);
	}

	private void synchronizeToStatementBoundary() {
		while (look != null && look.kind != TokenKind.EOF && look.kind != TokenKind.Rbrace) {
			if (look.kind == TokenKind.Semicolon) {
				move();
				return;
			}
			move();
		}
	}

	private Ast.Stmt.T parseStmt() throws IOException {
		Ast.Stmt.T stmt = null;
		
		if( look.kind == TokenKind.Printf ){
			match(new Token(TokenKind.Printf));
			match(new Token(TokenKind.Lparen));
			if (look.kind != TokenKind.String) {
				error("the first printf argument must be a format string");
			}
			String format = look.lexeme;
			int lineNumber = look.lineNumber;
			match(new Token(TokenKind.String));
			ArrayList<Ast.Expr.T> exprs = new ArrayList<>();
			while( look.kind == TokenKind.Comma ){
				match(new Token(TokenKind.Comma));
				exprs.add(parseExpr());
			}
			match( new Token(TokenKind.Rparen) );
			match( new Token(TokenKind.Semicolon) );
			stmt = new Ast.Stmt.Printf(format,exprs,lineNumber);
		}
		else if( look.kind == TokenKind.PrintLine ){
			int lineNumber = look.lineNumber;
			match(new Token(TokenKind.PrintLine));
			match(new Token(TokenKind.Lparen));
			match(new Token(TokenKind.Rparen));
			match( new Token(TokenKind.Semicolon) );
			stmt = new Ast.Stmt.PrintLine();
		}
		else if( look.kind == TokenKind.Break ){
			int lineNumber = look.lineNumber;
			match(new Token(TokenKind.Break));
			match(new Token(TokenKind.Semicolon));
			stmt = new Ast.Stmt.Break(lineNumber);
		}
		else if( look.kind == TokenKind.Continue ){
			int lineNumber = look.lineNumber;
			match(new Token(TokenKind.Continue));
			match(new Token(TokenKind.Semicolon));
			stmt = new Ast.Stmt.Continue(lineNumber);
		}
		else if( look.kind == TokenKind.While ){
			match(new Token(TokenKind.While));
			match(new Token(TokenKind.Lparen));
			int lineNumber = look.lineNumber;
			Ast.Expr.T condition = parseExpr();
			match(new Token(TokenKind.Rparen));
			Ast.Stmt.T whileStmt = parseStmt();
			stmt = new Ast.Stmt.While(condition, whileStmt, lineNumber);
		}
		else if( look.kind == TokenKind.For ){
			int lineNumber = look.lineNumber;
			match(new Token(TokenKind.For));
			match(new Token(TokenKind.Lparen));
			Ast.Stmt.T init = null;
			if (look.kind != TokenKind.Semicolon) {
				init = parseSimpleStmtWithoutTerminator();
			}
			match(new Token(TokenKind.Semicolon));
			Ast.Expr.T condition = look.kind == TokenKind.Semicolon
					? new Ast.Expr.True(lineNumber)
					: parseExpr();
			match(new Token(TokenKind.Semicolon));
			Ast.Stmt.T update = null;
			if (look.kind != TokenKind.Rparen) {
				update = parseSimpleStmtWithoutTerminator();
			}
			match(new Token(TokenKind.Rparen));
			Ast.Stmt.T body = parseStmt();
			stmt = new Ast.Stmt.For(init, condition, update, body, lineNumber);
		}
		else if ( look.kind == TokenKind.Id ) {
			Token ahead = lexer.lookahead(1);
			
			// Method call
			if( ahead.kind == TokenKind.Lparen ){
				String mthName = look.lexeme;
				int lineNumber = look.lineNumber;
				Ast.Expr.T expr =  parseMethodCall();
				if( expr instanceof Ast.Expr.Call){
					stmt = new Ast.Stmt.Call(mthName,((Ast.Expr.Call)expr).getInputParams(),lineNumber);
					match(new Token(TokenKind.Semicolon));
				}

			}
			// Array assignment: arr[i] = expr;
			else if( ahead.kind == TokenKind.Lbracket ){
				Token arrayToken = look;
				String arrayName = look.lexeme;
				int lineNum = look.lineNumber;
				match( new Token(TokenKind.Id) );
				match( "[" );
				Ast.Expr.T index = parseExpr();
				match( "]" );
				match( new Token(TokenKind.Assign) );
				Ast.Expr.T expr = parseExpr();
				match( new Token(TokenKind.Semicolon) );
				stmt = new Ast.Stmt.ArrayAssign(arrayName, index, expr, lineNum);
				stmt.setSpan(tokenSpan(arrayToken));
			}
			else{
				String id = look.lexeme;
				int lineNum = look.lineNumber;
				Token idToken = look;
				match( new Token(TokenKind.Id) );
				match( new Token(TokenKind.Assign) );
				Ast.Expr.T expr = parseExpr();
				match( new Token(TokenKind.Semicolon) );
				Ast.Expr.Id target = new Ast.Expr.Id(id, lineNum);
				target.setSpan(tokenSpan(idToken));
				stmt = new Ast.Stmt.Assign(target, expr, lineNum);
				
			}
		}
		else if( look.kind == TokenKind.Lbrace ) {
			match( "{" );
			int lineNumber = look.lineNumber;
			stmt = new Ast.Stmt.Block(parseStmts(), lineNumber);
			match( "}" );

		}
		else if( look.kind == TokenKind.Return ) {
			match( "return" );
			int lineNumber = look.lineNumber;
			Ast.Expr.T expr = parseExpr();
			stmt = new Ast.Stmt.Return(expr, lineNumber);
			match( ";" );

		}else if( look.kind == TokenKind.If ){
			match( "if" );
			match( "(" );
			int lineNumber = look.lineNumber;
			Ast.Expr.T condition = parseExpr();
			match( ")" );
			Ast.Stmt.T thenStmt = parseStmt();
			Ast.Stmt.T elseStmt = null;
			if( look.kind == TokenKind.Else){

				match( "else" );
				elseStmt = parseStmt();
			}

			stmt = new Ast.Stmt.If(condition, thenStmt, elseStmt, lineNumber);
		}
		return stmt;
	}

	private Ast.Stmt.T parseSimpleStmtWithoutTerminator() throws IOException {
		if (look.kind != TokenKind.Id) {
			error("expected an assignment or method call");
		}
		Token ahead = lexer.lookahead(1);
		if( ahead.kind == TokenKind.Lparen ){
			String mthName = look.lexeme;
			int lineNumber = look.lineNumber;
			Ast.Expr.T expr = parseMethodCall();
			if( expr instanceof Ast.Expr.Call){
				return new Ast.Stmt.Call(mthName,((Ast.Expr.Call)expr).getInputParams(),lineNumber);
			}
		}
		else if( ahead.kind == TokenKind.Lbracket ){
			String arrayName = look.lexeme;
			int lineNum = look.lineNumber;
			match( new Token(TokenKind.Id) );
			match( "[" );
			Ast.Expr.T index = parseExpr();
			match( "]" );
			match( new Token(TokenKind.Assign) );
			Ast.Expr.T expr = parseExpr();
			return new Ast.Stmt.ArrayAssign(arrayName, index, expr, lineNum);
		}
		else{
			Token idToken = look;
			String id = idToken.lexeme;
			int lineNum = idToken.lineNumber;
			match( new Token(TokenKind.Id) );
			match( new Token(TokenKind.Assign) );
			Ast.Expr.T expr = parseExpr();
			Ast.Expr.Id idExpr = new Ast.Expr.Id(id, lineNum);
			return new Ast.Stmt.Assign(idExpr, expr, lineNum);
		}
		error("could not parse simple statement");
		return null;
	}




	// Exp -> AndExp || AndExp
	//  -> AndExp
	private Ast.Expr.T parseExpr() throws IOException {
		Ast.Expr.T expr = parseAndExpr();
		while( look.kind == TokenKind.Or ) {
			move();
			Ast.Expr.T right = parseAndExpr();
			expr = new Ast.Expr.Or(expr, right, expr.getLineNum());
		}
		return expr;
	}



	// Exp -> AndExp && AndExp
	//  -> AndExp
	private Ast.Expr.T parseAndExpr() throws IOException {
		Ast.Expr.T expr = parseRelationExpr();
		while( look.kind == TokenKind.And) {
			move();
			Ast.Expr.T right = parseRelationExpr();
			expr = new Ast.Expr.And(expr, right, expr.getLineNum());
		}
		return expr;
	}

	// <relation_expr> -> additive_expr |<additive_expr>(>|<|>=|<=|==|!=)<additive_expr>
	private Ast.Expr.T parseRelationExpr() throws IOException {
		Ast.Expr.T expr = parseAdditiveExpr();
		while( look.kind == TokenKind.LT ||
				look.kind == TokenKind.GT ||
				look.kind == TokenKind.LTE ||
				look.kind == TokenKind.GTE ||
				look.kind == TokenKind.NEQ ||
				look.kind == TokenKind.EQ ) {
			String operator = look.lexeme;
			int lineNumber = look.lineNumber;
			move();
			Ast.Expr.T right = parseAdditiveExpr();
			expr = switch (operator) {
			case ">" -> new Ast.Expr.GT(expr, right, lineNumber);
			case "<" -> new Ast.Expr.LT(expr, right, lineNumber);
			case ">=" -> new Ast.Expr.GTE(expr, right, lineNumber);
			case "<=" -> new Ast.Expr.LTE(expr, right, lineNumber);
			case "==" -> new Ast.Expr.EQ(expr, right, lineNumber);
			case "!=" -> new Ast.Expr.NEQ(expr, right, lineNumber);
			default -> throw new CompilerException("Unexpected parser operator: " + operator);
			};

		}
		return expr;
	}

	//<additiveExpr>-><term>{(+|-)<term>}
	private Ast.Expr.T parseAdditiveExpr() throws IOException {
		Ast.Expr.T expr = parseTerm();
		while(look.kind==TokenKind.Add
				||look.kind==TokenKind.Sub) {
			Token opToken = look; // Operator token (+ or -)
			move();
			Ast.Expr.T otherExpr = parseTerm();
			if(opToken.kind==TokenKind.Add) {
				expr = new Ast.Expr.Add(expr, otherExpr, opToken.lineNumber);
			}else {
				expr = new Ast.Expr.Sub(expr, otherExpr, opToken.lineNumber);
			}
		}
		return expr;
	}

	// <term> -> <factor> *|/ <factor>
	private Ast.Expr.T parseTerm() throws IOException{
		Ast.Expr.T expr = parseFactor();
		while(look.kind==TokenKind.Mul
				||look.kind==TokenKind.Div
				||look.kind==TokenKind.Mod) {
			Token temp=look;
			move();
			Ast.Expr.T otherExpr = parseFactor();
			if(temp.kind == TokenKind.Mul) {
				expr = new Ast.Expr.Mul(expr, otherExpr, look.lineNumber);
			}else if(temp.kind == TokenKind.Div) {
				expr = new Ast.Expr.Div(expr, otherExpr, look.lineNumber);
			}else {
				expr = new Ast.Expr.Mod(expr, otherExpr, look.lineNumber);
			}
		}
		return expr;
	}


	// <factor> -> (<expression>)
	//  		| Integer Literal
	//  		| id
	//          | not(<expression>)
	private Ast.Expr.T parseFactor() throws IOException{
		Ast.Expr.T expr = null;
		if(look.kind==TokenKind.Lparen){
			move();
			expr = parseExpr();
			match(new Token(TokenKind.Rparen));
			return expr;
		}else if(look.kind==TokenKind.Sub){
			Token minusToken = look;
			int lineNumber = look.lineNumber;
			move();
			// The magnitude of Long.MIN_VALUE is one larger than Long.MAX_VALUE.
			// It is valid only when immediately preceded by unary minus.
			if(look.kind==Num && "9223372036854775808".equals(look.lexeme)) {
				Token numberToken = look;
				Ast.Expr.Number minLong = new Ast.Expr.Number(
						new Ast.Type.Long(), Long.MIN_VALUE, lineNumber);
				minLong.setSpan(tokenSpan(numberToken));
				move();
				return minLong;
			}
			Ast.Expr.T operand = parseFactor();
			Ast.Expr.Sub result = new Ast.Expr.Sub(
					new Ast.Expr.Number(new Ast.Type.Int(), 0, lineNumber), operand, lineNumber);
			result.setSpan(tokenSpan(minusToken));
			return result;
		}else if(look.kind== Num){
			Token numberToken = look;
			Ast.Type.T literalType;
			try {
				Integer.parseInt(look.lexeme);
				literalType = new Ast.Type.Int();
			} catch (NumberFormatException notInt) {
				try {
					Long.parseLong(look.lexeme);
					literalType = new Ast.Type.Long();
				} catch (NumberFormatException notLong) {
					error("integer literal is out of range for long");
					return null;
				}
			}
			expr = new Ast.Expr.Number(literalType,look.lexeme,look.lineNumber);
			expr.setSpan(tokenSpan(numberToken));
			move();
			return expr;
		}else if(look.kind==TokenKind.CharLiteral){
			Token charToken = look;
			expr = new Ast.Expr.Number(new Ast.Type.Char(), (int) charToken.lexeme.charAt(0), charToken.lineNumber);
			expr.setSpan(tokenSpan(charToken));
			move();
			return expr;
		}else if(look.kind==TokenKind.FloatLiteral){
			// Float literals default to float type (backwards compatibility)
			expr = new Ast.Expr.Number(new Ast.Type.Float(),look.lexeme,look.lineNumber);
			move();
			return expr;
		}else if( look.kind==TokenKind.Id ){
			Token temp = look; // Save id token
			Token ahead = lexer.lookahead(1);
			if( ahead.kind == TokenKind.Lparen){
				expr = parseMethodCall();
			}
			// Array access: arr[i]
			else if( ahead.kind == TokenKind.Lbracket){
				String arrayName = look.lexeme;
				int lineNum = temp.lineNumber;
				move(); // consume id
				match("[");
				Ast.Expr.T index = parseExpr();
				match("]");
				expr = new Ast.Expr.ArrayAccess(arrayName, index, lineNum);
				expr.setSpan(tokenSpan(temp));
			}
			else if( ahead.kind == TokenKind.Dot){
				String arrayName = look.lexeme;
				int lineNum = temp.lineNumber;
				move(); // consume id
				match(".");
				if (!"length".equals(look.lexeme)) {
					error("array property must be length");
				}
				match(new Token(TokenKind.Id));
				expr = new Ast.Expr.ArrayLength(arrayName, lineNum);
			}
			else{
				expr = new Ast.Expr.Id(look.lexeme, temp.lineNumber);
				expr.setSpan(tokenSpan(temp));
				move();
			}
			return expr;
		}
		else if(look.kind==TokenKind.String ){
			expr = new Ast.Expr.Str(look.lexeme, look.lineNumber);
			move();
			return expr;
		}
		else if(look.kind==TokenKind.Not ){
			move();
			match("(");
			expr = new Ast.Expr.Not(parseExpr());
			match(")");
			return expr;
		}
		else if(look.kind==TokenKind.True ){
			expr = new Ast.Expr.True(look.lineNumber);
			move();
			return expr;
		}
		else if(look.kind==TokenKind.False ){
			expr = new Ast.Expr.False(look.lineNumber);
			move();
			return expr;
		}
		else{
			throw diagnosticException(site.ilemon.diagnostic.DiagnosticCodes.PARSE_INVALID_EXPRESSION, String.format(
				"syntax error: expected an identifier, expression, number, or string, but found '%s'",
				look.lexeme));
		}
	}



	// methodCall->methodCall(Expr,Expr)
	private Ast.Expr.T parseMethodCall() throws IOException {
		Token ahead;
		Ast.Expr.T expr;
	String methodName = look.lexeme;
	Token methodToken = look;
		int lineNumber = look.lineNumber;
		move();
		match("(");
		ArrayList<Ast.Expr.T> args = null;
		args = new ArrayList<>();
		ahead = lexer.lookahead(1);
		if( look.kind == TokenKind.Rparen){

		}else{
			Ast.Expr.T e = parseExpr();
			args.add(e);
			while( look.kind == TokenKind.Comma){
				match(",");
				args.add(parseExpr());
			}
		}

		match(")");
		expr = new Ast.Expr.Call(methodName, args, lineNumber);
		expr.setSpan(tokenSpan(methodToken));
		return expr;
	}
}
