package site.ilemon.codegen;

import site.ilemon.codegen.ast.Ast;
import site.ilemon.ast.Ast.Type.TypeKind;

import java.io.IOException;
import site.ilemon.exception.CompilerException;

public class ByteCodeGenerator implements Visitor {

    public static final String DEFAULT_OUTPUT_DIR = "target/lemonc";

    private String currClassId;

    private java.io.BufferedWriter writer;

    private final java.io.File outputDir;

    private java.io.File outputFile;

    public ByteCodeGenerator() {
        this(new java.io.File(DEFAULT_OUTPUT_DIR));
    }

    public ByteCodeGenerator(java.io.File outputDir) {
        this.outputDir = outputDir;
    }

    public java.io.File getOutputDir() {
        return this.outputDir;
    }

    public java.io.File getOutputFile() {
        return this.outputFile;
    }

    public java.io.File getClassFile(String classId) {
        return new java.io.File(this.outputDir, classId + ".class");
    }

    private void writeln(String s)
    {
        write(s);
        write("\n");
    }

    private void write(String s)
    {
        try
        {
            this.writer.write(s);
        } catch (IOException e)
        {
            throw new CompilerException("IO Exception writing to file: " + e.getMessage());
        }
    }

    private void iwriteln(String s)
    {
        write("    " + s + "\n");
    }


    @Override
    public void visit(Ast.Program.ProgramSingle program) {
        this.visit(program.mainClass);
    }

    @Override
    public void visit(Ast.MainClass.MainClassSingle mainClassSingle) {
        this.currClassId = mainClassSingle.id;
        try {
            if (!this.outputDir.exists() && !this.outputDir.mkdirs()) {
                throw new IOException("Failed to create output directory: " + this.outputDir.getPath());
            }
            if (!this.outputDir.isDirectory()) {
                throw new IOException("Output path is not a directory: " + this.outputDir.getPath());
            }
            this.outputFile = new java.io.File(this.outputDir, mainClassSingle.id + ".il");
            this.writer = new java.io.BufferedWriter(new java.io.OutputStreamWriter(
                    new java.io.FileOutputStream(this.outputFile), "UTF-8"));
        } catch (Exception e)
        {
            throw new CompilerException("Failed to open output file for " + mainClassSingle.id + ": " + e.getMessage());
        }

        this.writeln("; This file is automatically generated by the compiler");
        this.writeln("; Do Not Modify!\n");

        this.writeln(".class public " + mainClassSingle.id);
        this.writeln(".super java/lang/Object");
        for( int i = 0; i < mainClassSingle.methods.size(); i++ ){
            this.visit(mainClassSingle.methods.get(i));
        }
        //this.iwriteln("return");
        //this.writeln(".end method");

        try
        {
            this.writer.close();
        } catch (IOException e)
        {
            throw new CompilerException("Failed to close output file: " + e.getMessage());
        }
    }

    public static int calculateMaxStack(java.util.List<Ast.Stmt.T> stmts) {
        if (stmts == null || stmts.isEmpty()) {
            return 0;
        }

        java.util.Map<String, Integer> labels = new java.util.HashMap<>();
        for (int i = 0; i < stmts.size(); i++) {
            Ast.Stmt.T stmt = stmts.get(i);
            if (stmt instanceof Ast.Stmt.LabelJ label) {
                labels.put(label.label.toString(), i);
            }
        }

        int[] inHeights = new int[stmts.size()];
        java.util.Arrays.fill(inHeights, -1);
        java.util.ArrayDeque<Integer> worklist = new java.util.ArrayDeque<>();
        inHeights[0] = 0;
        worklist.add(0);

        int max = 0;
        while (!worklist.isEmpty()) {
            int index = worklist.removeFirst();
            Ast.Stmt.T stmt = stmts.get(index);
            int current = inHeights[index];
            int localMax = current;
            int[] deltas = stackDeltas(stmt);

            for (int delta : deltas) {
                current += delta;
                if (current < 0) {
                    throw new CompilerException("Operand stack underflow after "
                            + stmt.getClass().getSimpleName() + " at IR index " + index);
                }
                if (current > localMax) {
                    localMax = current;
                }
            }
            if (localMax > max) {
                max = localMax;
            }

            for (Integer successor : successors(stmt, index, stmts.size(), labels)) {
                if (successor == null || successor < 0 || successor >= stmts.size()) {
                    continue;
                }
                int oldHeight = inHeights[successor];
                if (oldHeight == -1) {
                    inHeights[successor] = current;
                    worklist.add(successor);
                } else if (oldHeight != current) {
                    throw new CompilerException("Inconsistent operand stack height at IR index "
                            + successor + ": expected " + oldHeight + ", got " + current);
                }
            }
        }

        return max;
    }

    public static int calculateMaxLocals(Ast.Method.MethodSingle methodSingle) {
        if (methodSingle == null) {
            return 0;
        }

        int max = "main".equals(methodSingle.id) ? 1 : formalSlots(methodSingle.formals);
        if (methodSingle.stms != null) {
            for (Ast.Stmt.T stmt : methodSingle.stms) {
                int limit = localLimit(stmt);
                if (limit > max) {
                    max = limit;
                }
            }
        }
        return max;
    }

    private static java.util.List<Integer> successors(Ast.Stmt.T stmt, int index, int size,
                                                      java.util.Map<String, Integer> labels) {
        java.util.ArrayList<Integer> result = new java.util.ArrayList<>(2);
        if (stmt instanceof Ast.Stmt.Goto gotoStmt) {
            result.add(labelIndex(gotoStmt.l, labels));
            return result;
        }
        if (isReturn(stmt)) {
            return result;
        }
        if (isConditionalBranch(stmt)) {
            result.add(labelIndex(branchLabel(stmt), labels));
        }
        if (index + 1 < size) {
            result.add(index + 1);
        }
        return result;
    }

    private static Integer labelIndex(site.ilemon.codegen.ast.Label label,
                                      java.util.Map<String, Integer> labels) {
        Integer target = labels.get(label.toString());
        if (target == null) {
            throw new CompilerException("Missing label target: " + label);
        }
        return target;
    }

    private static boolean isConditionalBranch(Ast.Stmt.T stmt) {
        return stmt instanceof Ast.Stmt.Ifgt
                || stmt instanceof Ast.Stmt.Ificmplt
                || stmt instanceof Ast.Stmt.Ificmpgt
                || stmt instanceof Ast.Stmt.Ificmpge
                || stmt instanceof Ast.Stmt.Ificmple
                || stmt instanceof Ast.Stmt.Ificmpeq
                || stmt instanceof Ast.Stmt.Ificmpne;
    }

    private static site.ilemon.codegen.ast.Label branchLabel(Ast.Stmt.T stmt) {
        if (stmt instanceof Ast.Stmt.Ifgt branch) return branch.l;
        if (stmt instanceof Ast.Stmt.Ificmplt branch) return branch.l;
        if (stmt instanceof Ast.Stmt.Ificmpgt branch) return branch.l;
        if (stmt instanceof Ast.Stmt.Ificmpge branch) return branch.l;
        if (stmt instanceof Ast.Stmt.Ificmple branch) return branch.l;
        if (stmt instanceof Ast.Stmt.Ificmpeq branch) return branch.l;
        if (stmt instanceof Ast.Stmt.Ificmpne branch) return branch.l;
        throw new CompilerException("Internal error: not a conditional branch "
                + stmt.getClass().getSimpleName());
    }

    private static boolean isReturn(Ast.Stmt.T stmt) {
        return stmt instanceof Ast.Stmt.Ireturn
                || stmt instanceof Ast.Stmt.Freturn
                || stmt instanceof Ast.Stmt.Dreturn
                || stmt instanceof Ast.Stmt.Lreturn
                || stmt instanceof Ast.Stmt.Areturn;
    }

    private static int[] stackDeltas(Ast.Stmt.T stmt) {
        if (stmt instanceof Ast.Stmt.LabelJ || stmt instanceof Ast.Stmt.Goto) return deltas();
        if (stmt instanceof Ast.Stmt.Ldc ldc) return deltas(valueSlots(ldc.i));
        if (stmt instanceof Ast.Stmt.Iload || stmt instanceof Ast.Stmt.Fload
                || stmt instanceof Ast.Stmt.Aload) return deltas(1);
        if (stmt instanceof Ast.Stmt.Lload || stmt instanceof Ast.Stmt.Dload) return deltas(2);
        if (stmt instanceof Ast.Stmt.Istore || stmt instanceof Ast.Stmt.Fstore
                || stmt instanceof Ast.Stmt.Astore) return deltas(-1);
        if (stmt instanceof Ast.Stmt.Lstore || stmt instanceof Ast.Stmt.Dstore) return deltas(-2);

        if (stmt instanceof Ast.Stmt.Iadd || stmt instanceof Ast.Stmt.Isub
                || stmt instanceof Ast.Stmt.Imul || stmt instanceof Ast.Stmt.Idiv
                || stmt instanceof Ast.Stmt.Irem
                || stmt instanceof Ast.Stmt.Fadd || stmt instanceof Ast.Stmt.Fsub
                || stmt instanceof Ast.Stmt.Fmul || stmt instanceof Ast.Stmt.Fdiv
                || stmt instanceof Ast.Stmt.Fcmpl || stmt instanceof Ast.Stmt.Fcmpg) return deltas(-2, 1);
        if (stmt instanceof Ast.Stmt.Ladd || stmt instanceof Ast.Stmt.Lsub
                || stmt instanceof Ast.Stmt.Lmul || stmt instanceof Ast.Stmt.Ldiv
                || stmt instanceof Ast.Stmt.Lrem) return deltas(-4, 2);
        if (stmt instanceof Ast.Stmt.Lcmp) return deltas(-4, 1);
        if (stmt instanceof Ast.Stmt.Dadd || stmt instanceof Ast.Stmt.Dsub
                || stmt instanceof Ast.Stmt.Dmul || stmt instanceof Ast.Stmt.Ddiv) return deltas(-4, 2);
        if (stmt instanceof Ast.Stmt.Dcmpl || stmt instanceof Ast.Stmt.Dcmpg) return deltas(-4, 1);
        if (stmt instanceof Ast.Stmt.F2d) return deltas(-1, 2);
        if (stmt instanceof Ast.Stmt.I2f) return deltas();
        if (stmt instanceof Ast.Stmt.I2d) return deltas(-1, 2);
        if (stmt instanceof Ast.Stmt.I2l) return deltas(-1, 2);
        if (stmt instanceof Ast.Stmt.L2f) return deltas(-2, 1);
        if (stmt instanceof Ast.Stmt.L2d) return deltas(-2, 2);

        if (stmt instanceof Ast.Stmt.Ifgt) return deltas(-1);
        if (stmt instanceof Ast.Stmt.Ificmplt || stmt instanceof Ast.Stmt.Ificmpgt
                || stmt instanceof Ast.Stmt.Ificmpge || stmt instanceof Ast.Stmt.Ificmple
                || stmt instanceof Ast.Stmt.Ificmpeq || stmt instanceof Ast.Stmt.Ificmpne) return deltas(-2);

        if (stmt instanceof Ast.Stmt.Ireturn || stmt instanceof Ast.Stmt.Freturn
                || stmt instanceof Ast.Stmt.Areturn) return deltas(-1);
        if (stmt instanceof Ast.Stmt.Dreturn || stmt instanceof Ast.Stmt.Lreturn) return deltas(-2);

        if (stmt instanceof Ast.Stmt.Invokestatic call) {
            return deltas(-argumentTypeSlots(call.at), emittedReturnSlots(call.rt));
        }
        if (stmt instanceof Ast.Stmt.Printf printf) {
            return printfDeltas(printf.exprType);
        }
        if (stmt instanceof Ast.Stmt.PrintLine) return deltas(1, -2);
        if (stmt instanceof Ast.Stmt.Pop) return deltas(-1);
        if (stmt instanceof Ast.Stmt.Pop2) return deltas(-2);

        if (stmt instanceof Ast.Stmt.Newarray) return deltas(-1, 1);
        if (stmt instanceof Ast.Stmt.Iaload || stmt instanceof Ast.Stmt.Faload
                || stmt instanceof Ast.Stmt.Baload || stmt instanceof Ast.Stmt.Saload || stmt instanceof Ast.Stmt.Aaload) return deltas(-2, 1);
        if (stmt instanceof Ast.Stmt.Laload) return deltas(-2, 2);
        if (stmt instanceof Ast.Stmt.Daload) return deltas(-2, 2);
        if (stmt instanceof Ast.Stmt.Iastore || stmt instanceof Ast.Stmt.Fastore
                || stmt instanceof Ast.Stmt.Bastore || stmt instanceof Ast.Stmt.Sastore || stmt instanceof Ast.Stmt.Aastore) return deltas(-3);
        if (stmt instanceof Ast.Stmt.Lastore) return deltas(-4);
        if (stmt instanceof Ast.Stmt.Dastore) return deltas(-4);
        if (stmt instanceof Ast.Stmt.Arraylength) return deltas(-1, 1);

        throw new CompilerException("Missing stack effect for IR statement: "
                + stmt.getClass().getName());
    }

    private static int[] printfDeltas(Ast.Type.T type) {
        if (type != null && (type.getKind() == TypeKind.DOUBLE || type.getKind() == TypeKind.LONG)) {
            return deltas(1, 1, -1, -3);
        }
        return deltas(1, -2);
    }

    private static int argumentTypeSlots(java.util.List<Ast.Type.T> types) {
        int slots = 0;
        if (types != null) {
            for (Ast.Type.T type : types) {
                slots += typeSlots(type);
            }
        }
        return slots;
    }

    private static int formalSlots(java.util.List<Ast.Declare.DeclareSingle> declares) {
        int slots = 0;
        if (declares != null) {
            for (Ast.Declare.DeclareSingle declare : declares) {
                slots += typeSlots(declare.type);
            }
        }
        return slots;
    }

    private static int localLimit(Ast.Stmt.T stmt) {
        if (stmt instanceof Ast.Stmt.Iload load) return localLimit(load.index, 1);
        if (stmt instanceof Ast.Stmt.Fload load) return localLimit(load.index, 1);
        if (stmt instanceof Ast.Stmt.Aload load) return localLimit(load.index, 1);
        if (stmt instanceof Ast.Stmt.Dload load) return localLimit(load.index, 2);
        if (stmt instanceof Ast.Stmt.Lload load) return localLimit(load.index, 2);
        if (stmt instanceof Ast.Stmt.Istore store) return localLimit(store.index, 1);
        if (stmt instanceof Ast.Stmt.Fstore store) return localLimit(store.index, 1);
        if (stmt instanceof Ast.Stmt.Astore store) return localLimit(store.index, 1);
        if (stmt instanceof Ast.Stmt.Dstore store) return localLimit(store.index, 2);
        if (stmt instanceof Ast.Stmt.Lstore store) return localLimit(store.index, 2);
        return 0;
    }

    private static int localLimit(int index, int slots) {
        if (index < 0) {
            throw new CompilerException("Negative local variable index: " + index);
        }
        return index + slots;
    }

    private static int emittedReturnSlots(Ast.Type.T type) {
        if (type == null || type.getKind() == TypeKind.VOID) return 0;
        if (type != null && (type.getKind() == TypeKind.DOUBLE || type.getKind() == TypeKind.LONG)) return 2;
        return 1;
    }

    private static int typeSlots(Ast.Type.T type) {
        if (type == null || type.getKind() == TypeKind.VOID) return 0;
        if (type != null && (type.getKind() == TypeKind.DOUBLE || type.getKind() == TypeKind.LONG)) return 2;
        return 1;
    }

    private static String typeDescriptor(Ast.Type.T type) {
        if (type == null) {
            throw new CompilerException("Missing JVM type descriptor for null type");
        }
        return switch (type.getKind()) {
            case INT, BOOL -> "I";
            case BYTE -> "B";
            case SHORT -> "S";
            case LONG -> "J";
            case FLOAT -> "F";
            case DOUBLE -> "D";
            case VOID -> "V";
            case STRING -> "Ljava/lang/String;";
            case INT_ARRAY -> "[I";
            case BYTE_ARRAY -> "[B";
            case SHORT_ARRAY -> "[S";
            case LONG_ARRAY -> "[J";
            case FLOAT_ARRAY -> "[F";
            case DOUBLE_ARRAY -> "[D";
            case BOOL_ARRAY -> "[Z";
            case STRING_ARRAY -> "[Ljava/lang/String;";
            default -> throw new CompilerException("Unsupported JVM type descriptor: " + type);
        };
    }

    private static int valueSlots(Object value) {
        return value instanceof java.lang.Double || value instanceof java.lang.Long ? 2 : 1;
    }

    private static int[] deltas(int... values) {
        return values;
    }

    @Override
    public void visit(Ast.Method.MethodSingle methodSingle) {
        int localsLimit = calculateMaxLocals(methodSingle);
        int stackLimit = calculateMaxStack(methodSingle.stms);
        
        if (methodSingle.id.equals("main")) {
            this.writeln(".method public static main([Ljava/lang/String;)V");
            this.writeln(".limit stack " + stackLimit);
            this.writeln(".limit locals " + localsLimit);
            for (int i = 0; i < methodSingle.stms.size(); i++) {
                this.visit(methodSingle.stms.get(i));
            }
            this.writeln("return");
        } else {
            this.write(".method static " + methodSingle.id + "(");
            if (methodSingle.formals != null) {
                for (int i = 0; i < methodSingle.formals.size(); i++) {
                    this.write(typeDescriptor(methodSingle.formals.get(i).type));
                }
            }
            this.write(")" + typeDescriptor(methodSingle.retType));
            this.writeln("");
            this.writeln(".limit stack " + stackLimit);
            this.writeln(".limit locals " + localsLimit);
            for (int i = 0; i < methodSingle.stms.size(); i++) {
                this.visit(methodSingle.stms.get(i));
            }
            if (methodSingle.retType != null && methodSingle.retType.getKind() == TypeKind.VOID) {
                this.writeln("return");
            }
        }
        this.writeln(".end method");
    }

    @Override
    public void visit(Ast.Type type) {

    }

    @Override
    public void visit(Ast.Declare.DeclareSingle declareSingle) {

    }

    @Override
    public void visit(Ast.Stmt.T stmt) {
        if (stmt != null) {
            stmt.accept(this);
        }
    }

    @Override
    public void visit(Ast.Stmt.Aload s) {
        this.iwriteln("aload " + s.index);
    }

    @Override
    public void visit(Ast.Stmt.Areturn s) {
        this.iwriteln("areturn " );
    }

    @Override
    public void visit(Ast.Stmt.Astore s) {
        this.iwriteln("astore " + s.index);
    }

    @Override
    public void visit(Ast.Stmt.Goto s) {
        this.iwriteln("goto " + s.l.toString());
    }

    @Override
    public void visit(Ast.Stmt.Iadd s) {
        this.iwriteln("iadd");
    }

    @Override
    public void visit(Ast.Stmt.Isub s) {
        this.iwriteln("isub");
    }

    @Override
    public void visit(Ast.Stmt.Imul s) {
        this.iwriteln("imul");
    }

    @Override
    public void visit(Ast.Stmt.Idiv s) {
        this.iwriteln("idiv");
    }

    @Override
    public void visit(Ast.Stmt.Irem s) {
        this.iwriteln("irem");
    }

    @Override
    public void visit(Ast.Stmt.Fadd s) {
        this.iwriteln("fadd");
    }

    @Override
    public void visit(Ast.Stmt.Fsub s) {
        this.iwriteln("fsub");
    }

    @Override
    public void visit(Ast.Stmt.Fmul s) {
        this.iwriteln("fmul");
    }

    @Override
    public void visit(Ast.Stmt.Fdiv s) {
        this.iwriteln("fdiv");
    }

    @Override
    public void visit(Ast.Stmt.Ificmplt s) {

        this.iwriteln("if_icmplt " + s.l.toString());
    }

    @Override
    public void visit(Ast.Stmt.Ifgt s) {

        this.iwriteln("ifgt " + s.l.toString());
    }

    @Override
    public void visit(Ast.Stmt.Fcmpl s) {

        this.iwriteln("fcmpl ");
    }

    @Override
    public void visit(Ast.Stmt.Fcmpg s) {
        this.iwriteln("fcmpg ");
    }

    @Override
    public void visit(Ast.Stmt.Ificmpgt s) {

        this.iwriteln("if_icmpgt " + s.l.toString());
    }

    @Override
    public void visit(Ast.Stmt.Ificmpge s) {
        this.iwriteln("if_icmpge " + s.l.toString());
    }

    @Override
    public void visit(Ast.Stmt.Ificmple s) {
        this.iwriteln("if_icmple " + s.l.toString());
    }

    @Override
    public void visit(Ast.Stmt.Ificmpeq s) {
        this.iwriteln("if_icmpeq " + s.l.toString());
    }

    @Override
    public void visit(Ast.Stmt.Ificmpne s) {
        this.iwriteln("if_icmpne " + s.l.toString());
    }

    @Override
    public void visit(Ast.Stmt.Iload s) {
        this.iwriteln("iload " + s.index);
    }

    @Override
    public void visit(Ast.Stmt.Invokestatic s) {
        this.write("    invokestatic " + currClassId + "/" + s.name + "(");
        for( int i = 0; i< s.at.size(); i++){
            this.write(typeDescriptor(s.at.get(i)));
        }
        this.write(")" + typeDescriptor(s.rt));

        this.writeln("");
    }

    @Override
    public void visit(Ast.Stmt.Ireturn s) {
        this.iwriteln("ireturn");
    }

    @Override
    public void visit(Ast.Stmt.Istore s) {
        this.iwriteln("istore " + s.index);
    }

    @Override
    public void visit(Ast.Stmt.LabelJ s) {
        this.writeln(s.label.toString() + ":");
    }

    @Override
    public void visit(Ast.Stmt.Ldc s) {
        // Double and long types require the ldc2_w instruction
        if (s.i instanceof java.lang.Double || s.i instanceof java.lang.Long) {
            // Append 'd' suffix to explicitly specify double type
            this.iwriteln("ldc2_w " + s.i + (s.i instanceof java.lang.Double ? "d" : ""));
        } else {
            this.iwriteln("ldc " + s.i);
        }
    }

    @Override
    public void visit(Ast.Stmt.Printf obj) {
        if( obj.exprType.getKind() == TypeKind.INT || obj.exprType.getKind() == TypeKind.BYTE || obj.exprType.getKind() == TypeKind.SHORT){
            this.iwriteln("getstatic java/lang/System/out Ljava/io/PrintStream;");
            this.iwriteln("swap");
            this.iwriteln("invokevirtual java/io/PrintStream/print(I)V");
        }
        else if( obj.exprType.getKind() == TypeKind.FLOAT){
            this.iwriteln("getstatic java/lang/System/out Ljava/io/PrintStream;");
            this.iwriteln("swap");
            this.iwriteln("invokevirtual java/io/PrintStream/print(F)V");
        }
        else if( obj.exprType.getKind() == TypeKind.DOUBLE){
            this.iwriteln("getstatic java/lang/System/out Ljava/io/PrintStream;");
            this.iwriteln("dup_x2");
            this.iwriteln("pop");
            this.iwriteln("invokevirtual java/io/PrintStream/print(D)V");
        }
        else if( obj.exprType.getKind() == TypeKind.LONG){
            this.iwriteln("getstatic java/lang/System/out Ljava/io/PrintStream;");
            this.iwriteln("dup_x2");
            this.iwriteln("pop");
            this.iwriteln("invokevirtual java/io/PrintStream/print(J)V");
        }
        else if( obj.exprType.getKind() == TypeKind.STRING){
            this.iwriteln("getstatic java/lang/System/out Ljava/io/PrintStream;");
            this.iwriteln("swap");
            this.iwriteln("invokevirtual java/io/PrintStream/print(Ljava/lang/String;)V");
        }
    }

    @Override
    public void visit(Ast.Stmt.PrintLine obj) {
        /*this.iwriteln("ldc \"\\n\"");
        this.iwriteln("astore 100 ");
        this.iwriteln("aload 100 ");*/
        this.iwriteln("getstatic java/lang/System/out Ljava/io/PrintStream;");
        this.iwriteln("swap");
        this.iwriteln("invokevirtual java/io/PrintStream/print(Ljava/lang/String;)V");
    }

    @Override
    public void visit(Ast.Stmt.Pop s) {
        this.iwriteln("pop");
    }

    @Override
    public void visit(Ast.Stmt.Pop2 s) {
        this.iwriteln("pop2");
    }

    @Override
    public void visit(Ast.Stmt.Freturn s) {
        this.iwriteln("freturn");
    }

    public void visit(Ast.Stmt.Lreturn s) { this.iwriteln("lreturn"); }
    public void visit(Ast.Stmt.Lstore s) { this.iwriteln("lstore " + s.index); }
    public void visit(Ast.Stmt.Lload s) { this.iwriteln("lload " + s.index); }
    public void visit(Ast.Stmt.Ladd s) { this.iwriteln("ladd"); }
    public void visit(Ast.Stmt.Lsub s) { this.iwriteln("lsub"); }
    public void visit(Ast.Stmt.Lmul s) { this.iwriteln("lmul"); }
    public void visit(Ast.Stmt.Ldiv s) { this.iwriteln("ldiv"); }
    public void visit(Ast.Stmt.Lrem s) { this.iwriteln("lrem"); }
    public void visit(Ast.Stmt.Lcmp s) { this.iwriteln("lcmp"); }
    public void visit(Ast.Stmt.I2l s) { this.iwriteln("i2l"); }
    public void visit(Ast.Stmt.L2f s) { this.iwriteln("l2f"); }
    public void visit(Ast.Stmt.L2d s) { this.iwriteln("l2d"); }

    @Override
    public void visit(Ast.Stmt.Fstore s) {
        this.iwriteln("fstore " + s.index);
    }

    @Override
    public void visit(Ast.Stmt.Fload s) {
        this.iwriteln("fload " + s.index);
    }

    public void visit(Ast.Stmt.Dadd s) {
        this.iwriteln("dadd");
    }

    public void visit(Ast.Stmt.Dsub s) {
        this.iwriteln("dsub");
    }

    public void visit(Ast.Stmt.Dmul s) {
        this.iwriteln("dmul");
    }

    public void visit(Ast.Stmt.Ddiv s) {
        this.iwriteln("ddiv");
    }

    public void visit(Ast.Stmt.Dload s) {
        this.iwriteln("dload " + s.index);
    }

    public void visit(Ast.Stmt.Dstore s) {
        this.iwriteln("dstore " + s.index);
    }

    public void visit(Ast.Stmt.Dreturn s) {
        this.iwriteln("dreturn");
    }

    public void visit(Ast.Stmt.Dcmpl s) {
        this.iwriteln("dcmpl");
    }

    public void visit(Ast.Stmt.Dcmpg s) {
        this.iwriteln("dcmpg");
    }

    public void visit(Ast.Stmt.F2d s) {
        this.iwriteln("f2d");
    }

    public void visit(Ast.Stmt.I2f s) {
        this.iwriteln("i2f");
    }

    public void visit(Ast.Stmt.I2d s) {
        this.iwriteln("i2d");
    }

    @Override
    public void visit(Ast.Type.T obj) {
        if (obj != null) {
            obj.accept(this);
        }
    }

    @Override
    public void visit(Ast.Type.Int obj) {
        this.write("I");
    }

    @Override
    public void visit(Ast.Type.Byte obj) {
        this.write("B");
    }

    @Override
    public void visit(Ast.Type.Short obj) {
        this.write("S");
    }

    @Override
    public void visit(Ast.Type.Long obj) {
        this.write("J");
    }

    @Override
    public void visit(Ast.Type.Float obj) {
        this.write("F");
    }

    public void visit(Ast.Type.Double obj) {
        this.write("D");
    }

    @Override
    public void visit(Ast.Type.Str obj) {

    }

    @Override
    public void visit(Ast.Type.StringArray obj) {

    }

    @Override
    public void visit(Ast.Type.ByteArray obj) {

    }

    @Override
    public void visit(Ast.Type.ShortArray obj) {

    }

    @Override
    public void visit(Ast.Type.LongArray obj) {

    }

    @Override
    public void visit(Ast.Type.Bool obj) {

    }

    // ========== Array-related instructions ==========

    public void visit(Ast.Stmt.Newarray s) {
        String type = switch (s.elementType) {
            case Ast.Type.Int i -> "int";
            case Ast.Type.Byte b -> "byte";
            case Ast.Type.Short shortType -> "short";
            case Ast.Type.Long l -> "long";
            case Ast.Type.Float f -> "float";
            case Ast.Type.Double d -> "double";
            case Ast.Type.Bool b -> "boolean";
            case Ast.Type.Str stringType -> "java/lang/String";
            default -> "int"; // default
        };
        this.iwriteln(s.elementType instanceof Ast.Type.Str ? "anewarray " + type : "newarray " + type);
    }

    public void visit(Ast.Stmt.Iaload s) {
        this.iwriteln("iaload");
    }

    public void visit(Ast.Stmt.Iastore s) {
        this.iwriteln("iastore");
    }

    public void visit(Ast.Stmt.Faload s) {
        this.iwriteln("faload");
    }

    public void visit(Ast.Stmt.Fastore s) {
        this.iwriteln("fastore");
    }

    public void visit(Ast.Stmt.Daload s) {
        this.iwriteln("daload");
    }

    public void visit(Ast.Stmt.Dastore s) {
        this.iwriteln("dastore");
    }

    public void visit(Ast.Stmt.Baload s) {
        this.iwriteln("baload");
    }

    @Override
    public void visit(Ast.Stmt.Saload s) {
        this.iwriteln("saload");
    }

    public void visit(Ast.Stmt.Laload s) {
        this.iwriteln("laload");
    }

    public void visit(Ast.Stmt.Bastore s) {
        this.iwriteln("bastore");
    }

    @Override
    public void visit(Ast.Stmt.Sastore s) {
        this.iwriteln("sastore");
    }

    public void visit(Ast.Stmt.Lastore s) {
        this.iwriteln("lastore");
    }

    public void visit(Ast.Stmt.Aaload s) {
        this.iwriteln("aaload");
    }

    public void visit(Ast.Stmt.Aastore s) {
        this.iwriteln("aastore");
    }

    public void visit(Ast.Stmt.Arraylength s) {
        this.iwriteln("arraylength");
    }
}
